# See http://readme.drone.io/usage/overview
pipeline:
  build:
    image: docker.kbt.io/php-geos/build-test:trisquel
    commands:
      - ./autogen.sh
      - ./configure
      - make
      - make check
