# See http://readme.drone.io/usage/overview
pipeline:
  build:
    image: docker.kbt.io/php-geos/build-test:trisquel
    pull: true
    commands:
      - export PATH=${PHP_BIN}:${PATH}
      - php --version
      - ./autogen.sh
      - ./configure
      - make
      - make check
matrix:
  PHP_BIN:
    - /opt/php-5.5.38/bin/
    - /opt/php-5.6.28/bin/
    - /opt/php-7.0.13/bin/
    - /opt/php-7.1.0/bin/
